ADD $s4, $zero, $s1
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
ADD $t0, $zero, $zero
